# ファイル：.github/workflows/glitch-corrupt-only.yml
name: Glitch Niconico Video (Corrupt Only)

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'グリッチをかけたいニコニコ動画のURL'
        required: true

jobs:
  corrupt-only:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg mkvtoolnix python3-pip
          pip3 install yt-dlp

      - name: Download video from NicoNico
        run: |
          yt-dlp "${{ github.event.inputs.video_url }}" -o input.mp4

      - name: Remux to MKV (preserve streams)
        run: |
          ffmpeg -y -i input.mp4 -c copy input.mkv

      - name: Corrupt MKV payload only
        run: |
          # ファイルサイズ取得
          SIZE=$(stat --printf="%s" input.mkv)
          # データ部の先頭（ヘッダがだいたい1MB以内に収まる想定）を避け、
          # 中間位置から破壊開始
          OFFSET=$(( SIZE / 2 ))
          echo "Corrupting 1KB at offset ${OFFSET}"
          # 1KiB をランダムバイトで上書き
          dd if=/dev/urandom of=input.mkv bs=1 count=1024 seek=$OFFSET conv=notrunc

      - name: Re-decode corrupted MKV → output.mp4
        run: |
          ffmpeg -y -err_detect ignore_err -i input.mkv \
            -c:v libx264 -crf 23 -preset veryfast \
            -c:a copy \
            output.mp4

      - name: Commit and push glitched video
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 'Add glitched video (binary corrupt only)'
          add: 'output.mp4'
